require_relative 'sparkpost/version'
require_relative 'sparkpost/transmission'
require_relative 'sparkpost/client'
require_relative 'sparkpost/message_events'
require_relative 'sparkpost/metrics'
require_relative 'sparkpost/suppression_list'
require_relative 'sparkpost/template'
